# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='Miasto')),
                ('street', models.CharField(blank=True, max_length=128, verbose_name='Ulica')),
                ('house_nr', models.IntegerField(blank=True, null=True, verbose_name='Nr domu')),
                ('flat_nr', models.IntegerField(blank=True, null=True, verbose_name='Nr mieszkania')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'private'), (2, 'business')], null=True, verbose_name='Typ')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(blank=True, max_length=128, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=64, verbose_name='Imię')),
                ('last', models.CharField(blank=True, max_length=128, verbose_name='Nazwisko')),
                ('description', models.TextField(blank=True, default='', verbose_name='Opis')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContactBoxApp.Address', verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContactBoxApp.Groups')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContactBoxApp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Numer')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'home'), (2, 'mobile'), (3, 'business')], null=True, verbose_name='Typ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContactBoxApp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, through='ContactBoxApp.PersonGroups', to='ContactBoxApp.Groups'),
        ),
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContactBoxApp.Person'),
        ),
    ]
