# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBoxApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='groupname',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nowa grupa'),
        ),
        migrations.AlterField(
            model_name='persongroups',
            name='groups',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ContactBoxApp.Groups', verbose_name='Grupy'),
        ),
    ]
