# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBoxApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
