# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBoxApp', '0004_auto_20180510_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nr domu'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'private'), (2, 'business')], null=True, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContactBoxApp.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, to='ContactBoxApp.Groups'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'home'), (2, 'mobile'), (3, 'business')], null=True, verbose_name='Typ'),
        ),
    ]
