# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBoxApp', '0005_auto_20180510_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
